version: "3.8"

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - jproxy-payment1
      - jproxy-payment2
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 30M
    networks:
      - my-backend-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: redis-server --save 60 1 --loglevel warning --maxmemory 20mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: 20M
    networks:
      - my-backend-net

  jproxy-payment1:
    image: villanidev/rinha-de-backend-2025:1.0.0
    depends_on:
      - redis
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=http://redis:6379
      - INSTANCE_ID=1
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 150M
    networks:
      - my-backend-net
      - payment-processor

  jproxy-payment2:
    image: villanidev/rinha-de-backend-2025:1.0.0
    depends_on:
      - redis
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=http://redis:6379
      - INSTANCE_ID=2
      - DEFAULT_PROCESSOR_URL=http://payment-processor-default:8080
      - FALLBACK_PROCESSOR_URL=http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: 150M
    networks:
      - my-backend-net
      - payment-processor

networks:
  my-backend-net:
    driver: bridge
  payment-processor:
    external: true
